### PR TITLE
Add support for Laravel 10 and new GitHub Action

### PR DESCRIPTION
**Pull request by cfuentessalgado**
Hi folks!

This PR adds support for Laravel 10 and a new GitHub action to the project. With this update, users can now test their changes against the latest version of Laravel and take advantage of the new features and improvements it provides.

The new GitHub action uses a matrix to test against different combinations of PHP and Laravel versions, ensuring compatibility with a wider range of environments.

I've tested this in my fork of the project and all tests passed successfully. Please let me know if there's anything I can do to improve this PR or if you have any questions or concerns.

Thank you for your time and consideration!

Best regards,
Cristian.

---
image

### CODE REVIEW

**Comment by chrisbeaver** [comment]
Is there any intent on merging this?

**Comment by gpressutto5** [comment]
You did a great job on that, but I'm not planning on adding new features or maintaining it anymore so I just removed all version constraints in c9da40a0eada52ee628bfd6bb4c5b0cf3a5069bb. I did not merge it earlier because Scrutinizer was failing. I don't want to fix it as GH Actions is a much better tool, so I'm disabling it. Could you update this PR to only include the GH actions and remove the Scrutinizer build badge from the readme? Thank you!

**Comment by cfuentessalgado** [comment]
@gpressutto5 I've made the changes you requested. Seems like Scrutinizer is still failing, but at least is no longer listed in the README. Thanks for your time!

**Review by gpressutto5 — APPROVED** [review]
Thank you!

**Pull request merged**
